### ISSUE TITLE
which files to include in the package?

### ISSUE THREAD

**Issue by TheHadiAhmadi** [ubeac/svelte-components#12]
for packaging I used rollup to compile all svelte files to a single js file.

wile searching about this I found an official template for components from svelte team
https://github.com/sveltejs/component-template

in last paragraphs of readme of this repository they say: 

> Your package.json has a "svelte" field pointing to src/index.js, which allows Svelte apps to import the source code directly, if they are using a bundler plugin like rollup-plugin-svelte or svelte-loader (where resolve.mainFields in your webpack config includes "svelte"). This is recommended.

I tried this method with svelte+ts file and had error.
if we use JSDocs in svelte files, we will not have problems.

**Comment by TheHadiAhmadi** [comment]
@ap-ubeac as I said before, we can build packages with sveltekit, today I tried sveltekit and generated a folder which it's contents were:

package/
  .gitignore
  Alert.svelte
  Alert.svelte.d.ts
  Card.svelte
  Card.svelte.d.ts
  package.json
  README.md

content of src/lib:

lib/
  Alert.svelte
  Card.svelte

the *.svelte.d.ts files were generated with svelte2tsx package.

**Comment by pournasserian** [comment]
@TheHadiAhmadi please use my username @pournasserian instead of admin @ap-ubeac

**Comment by pournasserian** [comment]
@TheHadiAhmadi can you please explain more? I didn't get if you have any question.

**Comment by TheHadiAhmadi** [comment]
I tried to only include compiled javascript bundle in the npm package with styles.

Package/
* index.js
* styles.css


But after checking that template and sveltekit package, I realized that we need to have source files somewhere in package too.

Package/
* Alert.svelte
* Card.svelte
....

**Comment by TheHadiAhmadi** [comment]
I don't have a specific question, I just wanted you to know what I was doing today and why I didn't started working on components yet
