### ISSUE TITLE
Carousel component buttons don't work if we remove carousel items

### ISSUE THREAD

**Issue by TheHadiAhmadi** [ubeac/svelte-components#122]

**Comment by saadeghi** [comment]
@TheHadiAhmadi Can you provide a sample page on [TailwindPlay](https://play.tailwindcss.com/OTLrcz3eTU) or a GitHub repo?

**Comment by TheHadiAhmadi** [comment]
I worked on this but I couldn't fix the problem.

if you know solution, you can take this issue and work on it. or add your comments and suggestions here.

thanks

**Comment by TheHadiAhmadi** [comment]
carousel's images should be dynamic.


we should be able to add or remove images on runtime
Next and previous buttons should work correctly
